<template>
  <div class="about pa-6">
    <h1>This is an about page</h1>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime iure quae nisi obcaecati asperiores nihil molestias voluptatem porro sunt magni molestiae consequuntur totam vitae facilis velit, deserunt ut tempora soluta. Natus suscipit dolor tempore nesciunt nihil quasi voluptate tempora repellendus fugit rem dolore corporis reiciendis deleniti totam, molestias ratione similique!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime iure quae nisi obcaecati asperiores nihil molestias voluptatem porro sunt magni molestiae consequuntur totam vitae facilis velit, deserunt ut tempora soluta. Natus suscipit dolor tempore nesciunt nihil quasi voluptate tempora repellendus fugit rem dolore corporis reiciendis deleniti totam, molestias ratione similique!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime iure quae nisi obcaecati asperiores nihil molestias voluptatem porro sunt magni molestiae consequuntur totam vitae facilis velit, deserunt ut tempora soluta. Natus suscipit dolor tempore nesciunt nihil quasi voluptate tempora repellendus fugit rem dolore corporis reiciendis deleniti totam, molestias ratione similique!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime iure quae nisi obcaecati asperiores nihil molestias voluptatem porro sunt magni molestiae consequuntur totam vitae facilis velit, deserunt ut tempora soluta. Natus suscipit dolor tempore nesciunt nihil quasi voluptate tempora repellendus fugit rem dolore corporis reiciendis deleniti totam, molestias ratione similique!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime iure quae nisi obcaecati asperiores nihil molestias voluptatem porro sunt magni molestiae consequuntur totam vitae facilis velit, deserunt ut tempora soluta. Natus suscipit dolor tempore nesciunt nihil quasi voluptate tempora repellendus fugit rem dolore corporis reiciendis deleniti totam, molestias ratione similique!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime iure quae nisi obcaecati asperiores nihil molestias voluptatem porro sunt magni molestiae consequuntur totam vitae facilis velit, deserunt ut tempora soluta. Natus suscipit dolor tempore nesciunt nihil quasi voluptate tempora repellendus fugit rem dolore corporis reiciendis deleniti totam, molestias ratione similique!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime iure quae nisi obcaecati asperiores nihil molestias voluptatem porro sunt magni molestiae consequuntur totam vitae facilis velit, deserunt ut tempora soluta. Natus suscipit dolor tempore nesciunt nihil quasi voluptate tempora repellendus fugit rem dolore corporis reiciendis deleniti totam, molestias ratione similique!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime iure quae nisi obcaecati asperiores nihil molestias voluptatem porro sunt magni molestiae consequuntur totam vitae facilis velit, deserunt ut tempora soluta. Natus suscipit dolor tempore nesciunt nihil quasi voluptate tempora repellendus fugit rem dolore corporis reiciendis deleniti totam, molestias ratione similique!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime iure quae nisi obcaecati asperiores nihil molestias voluptatem porro sunt magni molestiae consequuntur totam vitae facilis velit, deserunt ut tempora soluta. Natus suscipit dolor tempore nesciunt nihil quasi voluptate tempora repellendus fugit rem dolore corporis reiciendis deleniti totam, molestias ratione similique!</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Maxime iure quae nisi obcaecati asperiores nihil molestias voluptatem porro sunt magni molestiae consequuntur totam vitae facilis velit, deserunt ut tempora soluta. Natus suscipit dolor tempore nesciunt nihil quasi voluptate tempora repellendus fugit rem dolore corporis reiciendis deleniti totam, molestias ratione similique!</p>
  </div>
</template>
